sonar.projectKey=enterprise-commerce
sonar.projectName=Enterprise Multi-Region E-Commerce Platform
sonar.sources=ecommerce_platform,services
sonar.tests=tests
sonar.exclusions=**/vendor/**,terraform/**,helm/**,kubernetes/**
